version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: log-manager-api
    environment:
      - DATABASE_URL=mongodb://test:test@db:27017/test
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db

  db:
    container_name: log-manager-db
    image: mongo
    volumes:
      - ./data:/data/db
      - ./.docker/init:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_USERNAME=test
      - MONGO_INITDB_PASSWORD=test

networks:
  webnet:
